CREATE TABLE IF NOT EXISTS backend_errors_localization (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(32) NOT NULL REFERENCES backend_errors(code) ON DELETE CASCADE,
    language VARCHAR(3) NOT NULL,
    message VARCHAR(255),
    UNIQUE(code, language)
);
