CREATE TABLE note_links (
    link_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_note_id UUID NOT NULL REFERENCES notes(note_id) ON DELETE CASCADE,
    to_note_id UUID NOT NULL REFERENCES notes(note_id) ON DELETE CASCADE,
    weight INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE note_links
ADD CONSTRAINT uq_note_links_pair UNIQUE(from_note_id, to_note_id);

CREATE INDEX ix_note_links_from ON note_links(from_note_id);
CREATE INDEX ix_note_links_to ON note_links(to_note_id);