// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv0DsvyZB95HdMr_LnUmBJywXraWPX7WI',
    appId: '1:162280543292:web:10865e5fe789c8c39a1f39',
    messagingSenderId: '162280543292',
    projectId: 'flux-6e697',
    authDomain: 'flux-6e697.firebaseapp.com',
    storageBucket: 'flux-6e697.firebasestorage.app',
    measurementId: 'G-6CTTFMZJ2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0CX74WpByaooyuBbmlTSFPKaL5k0fkWA',
    appId: '1:162280543292:android:32666429896306369a1f39',
    messagingSenderId: '162280543292',
    projectId: 'flux-6e697',
    storageBucket: 'flux-6e697.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsTF3-x9Whqg6X_k-q1HeO2Zytuwgbu4Q',
    appId: '1:162280543292:ios:6fa7b3210ad1624c9a1f39',
    messagingSenderId: '162280543292',
    projectId: 'flux-6e697',
    storageBucket: 'flux-6e697.firebasestorage.app',
    iosBundleId: 'online.pipipopi.flux',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsTF3-x9Whqg6X_k-q1HeO2Zytuwgbu4Q',
    appId: '1:162280543292:ios:40bf7a67960c02759a1f39',
    messagingSenderId: '162280543292',
    projectId: 'flux-6e697',
    storageBucket: 'flux-6e697.firebasestorage.app',
    iosBundleId: 'com.example.front',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv0DsvyZB95HdMr_LnUmBJywXraWPX7WI',
    appId: '1:162280543292:web:ec9cedd531cfeb269a1f39',
    messagingSenderId: '162280543292',
    projectId: 'flux-6e697',
    authDomain: 'flux-6e697.firebaseapp.com',
    storageBucket: 'flux-6e697.firebasestorage.app',
    measurementId: 'G-NMFZ89VE67',
  );
}
