name: front
description: "Flux - cross-platform notes, reminders and knowledge graph app"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # device info
  package_info_plus: ^8.0.0
  device_info_plus: ^11.0.0

  # routing
  go_router: ^17.2.1
  url_launcher: ^6.3.2

  # state management
  flutter_riverpod: ^3.3.1

  # local storage 
  drift: ^2.20.0
  drift_flutter: ^0.2.0
  sqlite3_flutter_libs: ^0.5.0

  # network
  dio: ^5.9.2
  http: ^1.6.0
  universal_io: ^2.3.1

  # auth / secure storage
  flutter_secure_storage: ^10.0.0

  # models / utils
  uuid: ^4.5.3
  intl: ^0.20.2

  # UI
  flutter_svg: ^2.2.4
  flutter_animate: ^4.5.2
  cached_network_image: ^3.4.1
  flutter_markdown: ^0.7.7+1
  markdown: ^7.3.1

  # device / desktop / web
  web: ^1.1.0
  window_manager: ^0.5.1
  app_links: ^7.1.2

  # уведомления firebase
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  permission_handler: ^11.3.0

  # файлы
  path_provider: ^2.1.5
  path: ^1.9.0
  image_picker: ^1.2.3
  mime: ^2.0.0
  record: ^7.1.1
  just_audio: ^0.10.6
  just_audio_windows: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  drift_dev: ^2.20.0
  build_runner: ^2.4.9
  package_rename: ^1.10.1
  icons_launcher: ^3.1.0

package_rename_config:
  android:
    app_name: Flux
    package_name: online.pipipopi.flux

  ios:
    app_name: Flux
    bundle_name: Flux
    bundle_identifier: online.pipipopi.flux

  macos:
    app_name: Flux
    bundle_name: Flux
    bundle_identifier: online.pipipopi.flux

  web:
    app_name: Flux
    description: Flux

  linux:
    app_name: Flux
    package_name: flux

  windows:
    app_name: Flux
    organization_name: Misha_dev
    copyright_notice: Misha_dev

icons_launcher:
  image_path: "assets/img/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    macos:
      enable: true
    windows:
      enable: true
    linux:
      enable: true
    web:
      enable: true

flutter:
  generate: true
  uses-material-design: true
  config:
    enable-swift-package-manager: false

  assets:
    - assets/img/
  fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
        weight: 400
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
      - asset: assets/fonts/Montserrat-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700

  - family: MontserratAlternates
    fonts:
      - asset: assets/fonts/MontserratAlternates-Light.ttf
        weight: 300
      - asset: assets/fonts/MontserratAlternates-Regular.ttf
        weight: 400
      - asset: assets/fonts/MontserratAlternates-Medium.ttf
        weight: 500
